name: Build AppImage

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Pull Qt Docker image
      run: docker pull carlonluca/qt-dev:6.5.2

    - name: Build AppImage in Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace carlonluca/qt-dev:6.5.2 bash -c "

          mkdir build && cd build
          /opt/qt/6.5.2/gcc_64/bin/qt-cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
          cmake --build .
          make install DESTDIR=AppDir

          mkdir -p AppDir/usr/share/icons
          cp ../images/logo.svg AppDir/usr/share/icons

          cd ..
          sed -i 's/version: .*/version: ${{ github.event.release.tag_name }}/' AppImageBuilder.yml

          appimage-builder --recipe AppImageBuilder.yml
        "

    - name: Upload AppImage
      uses: softprops/action-gh-release@v1
      with:
        files: '*.AppImage'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
